"""Tests for the VirtualDJ censor list generator."""

import subprocess
import sys
from pathlib import Path

import pytest
import yaml

import main

REPO_ROOT = Path(__file__).parent.parent
LISTS_DIR = REPO_ROOT / "lists"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def generate_to_tmp(tmp_path, policy="precision"):
    """Run generate() into a temp directory and return the three output files."""
    main.generate(policy, tmp_path)
    files = {}
    for fname in ["no-slurs-no-sex.txt", "conventions.txt", "child-friendly.txt"]:
        files[fname] = (tmp_path / fname).read_text()
    return files


def parse_terms(text):
    """Parse a space-separated output file into a set of terms."""
    return set(text.split()) if text.strip() else set()


def load_all_forms(yaml_filename):
    """Load all forms from a YAML list file."""
    data = yaml.safe_load((LISTS_DIR / yaml_filename).read_text())
    forms = []
    for entry in data["words"]:
        forms.extend(entry["forms"])
    return forms


# ---------------------------------------------------------------------------
# YAML structure tests
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("yaml_file", [
    "slurs.yaml",
    "sexual-content.yaml",
    "severe-swear-words.yaml",
    "other-swear-words.yaml",
])
def test_yaml_valid_and_structured(yaml_file):
    """Every YAML file is valid and uses structured entries with term + forms."""
    data = yaml.safe_load((LISTS_DIR / yaml_file).read_text())
    assert "words" in data
    for entry in data["words"]:
        assert "term" in entry, f"Missing 'term' in {yaml_file}: {entry}"
        assert "forms" in entry, f"Missing 'forms' in {yaml_file}: {entry}"
        assert isinstance(entry["forms"], list)
        assert len(entry["forms"]) > 0


def test_no_bare_strings_in_yaml():
    """No YAML entry should be a bare string — all must be structured."""
    for yaml_file in LISTS_DIR.glob("*.yaml"):
        data = yaml.safe_load(yaml_file.read_text())
        for entry in data["words"]:
            assert isinstance(entry, dict), \
                f"Bare string '{entry}' found in {yaml_file.name}"


# ---------------------------------------------------------------------------
# Nonsense forms eliminated
# ---------------------------------------------------------------------------

NONSENSE_FORMS = [
    "fuck'll", "fuck'd", "shit'll", "shit'd", "bitch'll", "bitch'd",
    "fag'll", "fag'd", "faggot'll", "faggot'd",
    "fages", "faggotes", "niggaes", "niggeres", "gypsyes",
    "dickes", "tites", "pussyes", "bastardes", "hornyes",
    "hoees", "whorees", "cumes",
    "faggoting", "cuming", "whoreing", "hoeing",
    "bullshitin",  # wrong — should be bullshittin
    "fagin",       # wrong — not a real form of fag
]


@pytest.mark.parametrize("nonsense", NONSENSE_FORMS)
def test_nonsense_forms_absent(nonsense, tmp_path):
    """Nonsense forms from blanket suffix expansion must not appear."""
    files = generate_to_tmp(tmp_path)
    for fname, content in files.items():
        terms = parse_terms(content)
        assert nonsense not in terms, \
            f"Nonsense form '{nonsense}' found in {fname}"


# ---------------------------------------------------------------------------
# Real forms present
# ---------------------------------------------------------------------------

REAL_FORMS_THAT_WERE_MISSING = [
    "fucked",      # was not generated by old +s/+es suffixes
    "cumming",     # old code generated "cuming" (wrong)
    "whoring",     # old code generated "whoreing" (wrong)
    "whorin",      # old code generated "whorein" (wrong)
    "pissed",      # was not generated
    "asshole",     # was not in any list at all
    "motherfucked",  # was not generated
    "motherfuckin",  # was not generated (old code made "motherfuckin" but also "motherfuckin'll")
]


@pytest.mark.parametrize("form", REAL_FORMS_THAT_WERE_MISSING)
def test_real_forms_present(form, tmp_path):
    """Real English forms that were missing from the old generator are present."""
    files = generate_to_tmp(tmp_path, policy="recall")
    all_terms = set()
    for content in files.values():
        all_terms |= parse_terms(content)
    assert form in all_terms, f"Real form '{form}' is missing from all outputs"


def test_fuck_forms_complete(tmp_path):
    """The fuck entry has all expected real forms."""
    files = generate_to_tmp(tmp_path, policy="recall")
    all_terms = set()
    for content in files.values():
        all_terms |= parse_terms(content)
    expected = {"fuck", "fucks", "fuck's", "fuck!", "fucked",
                "fuckin", "fuckin'", "fucking", "fucker", "fuckers"}
    missing = expected - all_terms
    assert not missing, f"Missing fuck forms: {missing}"


def test_apostrophe_forms_present(tmp_path):
    """Apostrophe-bearing forms are present (quoted in YAML)."""
    files = generate_to_tmp(tmp_path, policy="recall")
    all_terms = set()
    for content in files.values():
        all_terms |= parse_terms(content)
    for form in ["fuckin'", "bitchin'", "bullshittin'", "motherfuckin'", "whorin'"]:
        assert form in all_terms, f"Apostrophe form '{form}' missing"


# ---------------------------------------------------------------------------
# No duplicates and deterministic ordering
# ---------------------------------------------------------------------------

def test_no_duplicates(tmp_path):
    """Each output file has no duplicate terms."""
    files = generate_to_tmp(tmp_path, policy="recall")
    for fname, content in files.items():
        terms = content.split()
        assert len(terms) == len(set(terms)), \
            f"Duplicates in {fname}: {len(terms)} total, {len(set(terms))} unique"


def test_deterministic(tmp_path):
    """Generating twice produces identical output."""
    main.generate("recall", tmp_path)
    first = {f: (tmp_path / f).read_text()
             for f in ["no-slurs-no-sex.txt", "conventions.txt", "child-friendly.txt"]}

    tmp2 = tmp_path / "second"
    main.generate("recall", tmp2)
    second = {f: (tmp2 / f).read_text()
              for f in ["no-slurs-no-sex.txt", "conventions.txt", "child-friendly.txt"]}

    for fname in first:
        assert first[fname] == second[fname], \
            f"Non-deterministic output for {fname}"


def test_sorted(tmp_path):
    """Terms in each output file are sorted."""
    files = generate_to_tmp(tmp_path, policy="recall")
    for fname, content in files.items():
        terms = content.split()
        assert terms == sorted(terms), f"{fname} is not sorted"


# ---------------------------------------------------------------------------
# Cumulative membership
# ---------------------------------------------------------------------------

def test_cumulative_membership(tmp_path):
    """Each file is a superset of the previous severity tier."""
    files = generate_to_tmp(tmp_path, policy="recall")
    nsns = parse_terms(files["no-slurs-no-sex.txt"])
    conv = parse_terms(files["conventions.txt"])
    child = parse_terms(files["child-friendly.txt"])

    assert nsns <= conv, "conventions.txt missing terms from no-slurs-no-sex.txt"
    assert conv <= child, "child-friendly.txt missing terms from conventions.txt"


def test_cumulative_growth(tmp_path):
    """Each file has more terms than the previous tier."""
    files = generate_to_tmp(tmp_path, policy="recall")
    nsns = len(parse_terms(files["no-slurs-no-sex.txt"]))
    conv = len(parse_terms(files["conventions.txt"]))
    child = len(parse_terms(files["child-friendly.txt"]))
    assert nsns < conv < child, \
        f"Expected increasing counts: {nsns} < {conv} < {child}"


# ---------------------------------------------------------------------------
# Ambiguous policy: ho
# ---------------------------------------------------------------------------

def test_precision_omits_ho(tmp_path):
    """Precision policy omits 'ho' and its forms from all outputs."""
    files = generate_to_tmp(tmp_path, policy="precision")
    for fname, content in files.items():
        terms = parse_terms(content)
        for ho_form in ["ho", "hos", "ho's"]:
            assert ho_form not in terms, \
                f"'{ho_form}' should be omitted in precision mode but found in {fname}"


def test_recall_includes_ho(tmp_path):
    """Recall policy includes 'ho' and its forms in outputs."""
    files = generate_to_tmp(tmp_path, policy="recall")
    # ho is in sexual-content.yaml, so it should be in all three cumulative files
    for fname, content in files.items():
        terms = parse_terms(content)
        assert "ho" in terms, f"'ho' should be present in recall mode but missing from {fname}"


def test_precision_omits_only_ho(tmp_path):
    """Precision mode omits only 'ho' — no other term should be dropped."""
    files_recall = generate_to_tmp(tmp_path, policy="recall")
    files_precision = generate_to_tmp(tmp_path, policy="precision")

    recall_terms = set()
    precision_terms = set()
    for content in files_recall.values():
        recall_terms |= parse_terms(content)
    for content in files_precision.values():
        precision_terms |= parse_terms(content)

    removed = recall_terms - precision_terms
    # Only ho-family terms should be removed
    assert removed == {"ho", "hos", "ho's"}, \
        f"Precision removed unexpected terms: {removed}"


# ---------------------------------------------------------------------------
# CLI / subprocess tests
# ---------------------------------------------------------------------------

def test_cli_default_precision(tmp_path):
    """Running main.py with no args uses precision policy."""
    result = subprocess.run(
        [sys.executable, str(REPO_ROOT / "main.py"),
         "--output-dir", str(tmp_path)],
        capture_output=True, text=True,
    )
    assert result.returncode == 0
    terms = parse_terms((tmp_path / "no-slurs-no-sex.txt").read_text())
    assert "ho" not in terms


def test_cli_recall(tmp_path):
    """Running main.py with --ambiguous-policy recall includes ho."""
    result = subprocess.run(
        [sys.executable, str(REPO_ROOT / "main.py"),
         "--ambiguous-policy", "recall",
         "--output-dir", str(tmp_path)],
        capture_output=True, text=True,
    )
    assert result.returncode == 0
    terms = parse_terms((tmp_path / "no-slurs-no-sex.txt").read_text())
    assert "ho" in terms


def test_cli_omitted_logged_to_stderr(tmp_path):
    """Precision mode logs omitted ambiguous terms to stderr."""
    result = subprocess.run(
        [sys.executable, str(REPO_ROOT / "main.py"),
         "--output-dir", str(tmp_path)],
        capture_output=True, text=True,
    )
    assert "Omitted ambiguous terms" in result.stderr
    assert "ho" in result.stderr


def test_cli_term_counts_in_stderr(tmp_path):
    """Stderr includes term counts for each output file."""
    result = subprocess.run(
        [sys.executable, str(REPO_ROOT / "main.py"),
         "--output-dir", str(tmp_path)],
        capture_output=True, text=True,
    )
    for fname in ["no-slurs-no-sex.txt", "conventions.txt", "child-friendly.txt"]:
        assert fname in result.stderr


# ---------------------------------------------------------------------------
# Output format tests
# ---------------------------------------------------------------------------

def test_output_not_empty(tmp_path):
    """All output files are non-empty."""
    files = generate_to_tmp(tmp_path)
    for fname, content in files.items():
        assert content.strip(), f"{fname} is empty"


def test_output_only_ascii(tmp_path):
    """Output contains only ASCII characters (VirtualDJ compatibility)."""
    files = generate_to_tmp(tmp_path, policy="recall")
    for fname, content in files.items():
        try:
            content.encode("ascii")
        except UnicodeEncodeError:
            pytest.fail(f"{fname} contains non-ASCII characters")


def test_no_regex_syntax_in_output(tmp_path):
    """Output contains only literal terms, no regex metacharacters."""
    files = generate_to_tmp(tmp_path, policy="recall")
    # Apostrophes and hyphens are OK (literal characters). Backslashes,
    # brackets, parens, pipes, carets, dollar signs are not.
    forbidden = {"\\", "[", "]", "(", ")", "|", "^", "$", "*", "+", "?"}
    for fname, content in files.items():
        for ch in forbidden:
            assert ch not in content, \
                f"Regex metacharacter '{ch}' found in {fname}"
